steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gsd-ai-mx-ulises/app-repo/bank-campaign-model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gsd-ai-mx-ulises/app-repo/bank-campaign-model']

- name: 'us-central1-docker.pkg.dev/gsd-ai-mx-ulises/app-repo/bank-campaign-model'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/ulises-jimenez07/model-training-repo.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'model-training-repo/bank_campaign_model_training.py', 'gs://us-central1-mlops-airflow-50d68178-bucket/dags']

images:
- 'us-central1-docker.pkg.dev/gsd-ai-mx-ulises/app-repo/bank-campaign-model'

options:
  logging: CLOUD_LOGGING_ONLY